INSERT INTO authors(f_name, l_name, name, image)
VALUES("J. K.", "Rowling", CONCAT(f_name, ' ', l_name), "https://images.gr-assets.com/authors/1510435123p5/1077326.jpg"),
    ("Thomas H.", "Cormen", CONCAT(f_name, ' ', l_name), "https://images-na.ssl-images-amazon.com/images/I/21+jGufWIzL._UX250_.jpg"),
    ("Ronald L.", "Rivest", CONCAT(f_name, ' ', l_name), "https://images-na.ssl-images-amazon.com/images/I/61PAgQJP9SL._UX250_.jpg"),
    ("Charles E.", "Leiserson", CONCAT(f_name, ' ', l_name), "https://images-na.ssl-images-amazon.com/images/I/91M+2Ns8nJL._UX250_.jpg"),
    ("Clifford", "Stein", CONCAT(f_name, ' ', l_name), "https://images-na.ssl-images-amazon.com/images/I/71xnax+NE6L._UX250_.jpg"),
    ("Jeremy", "Kepner", CONCAT(f_name, ' ', l_name), "http://www.mit.edu/~kepner/MGHPCC02.jpg"),
    ("Kenneth P.", "Bogart", CONCAT(f_name, ' ', l_name), "https://www.math.dartmouth.edu/news-resources/electronic/kpbogart/bogart-classroom-crop.jpg"),
    ("Robert L.", "Drysdale", CONCAT(f_name, ' ', l_name), "https://home.dartmouth.edu/faculty-directory/sites/dartmouth.edu.faculty-directory/files/styles/profile_image/public/401_original.jpg?itok=MFdA5nV6"),
    ("Douglas", "Preston", CONCAT(f_name, ' ', l_name), "https://images-na.ssl-images-amazon.com/images/I/A1jwobwDBcL._UX250_.jpg"),
    ("Lincoln", "Child", CONCAT(f_name, ' ', l_name), "https://images-na.ssl-images-amazon.com/images/I/21fnoKPgAwL._UX250_.jpg"),
    ("Stephen", "King", CONCAT(f_name, ' ', l_name), "https://images-na.ssl-images-amazon.com/images/I/61dWUcBJ10L._UX250_.jpg"),
    ("Peter", "Straub", CONCAT(f_name, ' ', l_name), "https://images-na.ssl-images-amazon.com/images/I/61I+E36WgZL._UX250_.jpg"),
    ("Mary", "Higgins", CONCAT(f_name, ' ', l_name), "https://images-na.ssl-images-amazon.com/images/I/31GYnTs3M6L._UX250_.jpg"),
    ("Alafair", "Burke", CONCAT(f_name, ' ', l_name), "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0d/Alafair_Burke.jpg/220px-Alafair_Burke.jpg"),
    ("Neil", "Gaiman", CONCAT(f_name, ' ', l_name), "https://images-na.ssl-images-amazon.com/images/I/31EkV7IKxfL._UX250_.jpg"),
    ("Terry", "Pratchett", CONCAT(f_name, ' ', l_name), "https://images-na.ssl-images-amazon.com/images/I/31VE8a2Q2wL._UX250_.jpg");