INSERT INTO genres(genre_name)
VALUES  ("Fantasy"),
        ("Fiction"),
        ("Drama"),
        ("Mystery"),
        ("Thriller"),
        ("Computer Science"),
        ("Programming"),
        ("Mathematics"),
        ("Science Fiction"),
        ("Horror"),
        ("Dark Fantasy"),
        ("Horror Fiction"),
        ("Suspense"),
        ("Humor"),
        ("Adventure"),
        ("Classic"),
        ("Mystery Thriller"),
        ("Crime"),
        ("Urban Fantasy"),
        ("Mythology"),
        ("Comedy");